name: License Template Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:


jobs:
  license-check:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Check License Header
        run:  "scripts/rat.sh"
