name: Publish
on:
  release:
    branches: [main]
    types: [created]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.4"
        enable-cache: true
    - name: Sync build environment
      run: "uv sync --only-group build"
    - name: Build distribution
      run: "uv run hatch build"
    - name: Upload distribution artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI
    needs:
        - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/apache-dubbo/
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
