name: Lint and Test

on:
  push:
  pull_request:


jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.4"
          enable-cache: true

      - name: Sync development environment
        run: "uv sync"

      - name: Run Linter
        run: "scripts/lint.sh"


  tests:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.4"
          enable-cache: true

      - name: Sync environment with all extras
        run: " uv sync --all-extras"

      - name: Run Tests with Coverage
        run: "uv run pytest --cov=src/dubbo --cov-report=term-missing"
